name: Ruby Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.3', '3.4']
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
          cache-version: 1
      - name: Run tests
        run: bundle exec ruby -Ilib:test -e "Dir.glob('./test/**/*_test.rb').each { |f| require f }"
      - name: Run smoke test
        run: |
          chmod +x test/test_requests.sh
          test/test_requests.sh
